[book]
authors = ["Drv-Parts", "You"]
language = "en"
multilingual = false
src = "src"
title = "__TITLE__"

[output.html]
no-section-label = true

[output.html.print]
enable = false  # big single page; don't need that

[output.linkcheck]
follow-web-links = false # no Internet during the build
